### ISSUE TITLE
我的Python版本是3.6的，使用命令acmpv  +  url 报错如下

### ISSUE THREAD

**Issue by Whiood** [Vayn/acmpv#7]
Traceback (most recent call last):
  File "/usr/local/bin/acmpv", line 11, in <module>
    acmpv.main()
  File "/home/whiood/acmpv/src/acmpv/__main__.py", line 52, in main
    mpv = [make_path('mpv.sh'), '--force-media-title', title.replace(' ', '_')]
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by ddqp** [comment]
应该早就不能用了
